# Generated by Django 6.0.6 on 2026-07-07 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('Médecin de plantes', 'Médecin de plantes'), ('Vétérinaire', 'Vétérinaire')], max_length=30)),
                ('specialty', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('avatar_color', models.CharField(default='#2D5A3D', max_length=10)),
                ('online', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'experts',
            },
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Inscription'), ('reset_password', 'Réinitialisation')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'one_time_codes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur')], default='user', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('dioula', 'Dioula'), ('baoule', 'Baoulé'), ('bete', 'Bété'), ('senoufo', 'Sénoufo')], default='fr', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CropScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='scans/%Y/%m/')),
                ('crop_name', models.CharField(max_length=100)),
                ('disease_name', models.CharField(blank=True, max_length=150)),
                ('severity', models.CharField(choices=[('faible', 'Faible'), ('modérée', 'Modérée'), ('élevée', 'Élevée'), ('critique', 'Critique')], default='faible', max_length=10)),
                ('remedy', models.TextField(blank=True)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('symptoms', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0)),
                ('is_healthy', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('treated', 'Traitée'), ('resolved', 'Résolue')], default='active', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crop_scans',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('conversation_id', models.CharField(db_index=True, max_length=50)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_role', models.CharField(choices=[('farmer', 'Agriculteur'), ('expert', 'Expert')], default='farmer', max_length=10)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='expert_chat/%Y/%m/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_messages', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cropscan')),
            ],
            options={
                'db_table': 'expert_messages',
                'ordering': ['created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FertilizerCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('crop_type', models.CharField(choices=[('cacao', 'Cacao'), ('café', 'Café'), ('manioc', 'Manioc'), ('riz', 'Riz'), ('maïs', 'Maïs'), ('igname', 'Igname'), ('banane_plantain', 'Banane plantain'), ('hévéa', 'Hévéa'), ('palmier_huile', 'Palmier à huile'), ('coton', 'Coton')], max_length=30)),
                ('soil_type', models.CharField(choices=[('argileux', 'Argileux'), ('sableux', 'Sableux'), ('limoneux', 'Limoneux'), ('latéritique', 'Latéritique'), ('tourbeux', 'Tourbeux')], max_length=20)),
                ('surface_hectares', models.FloatField()),
                ('nitrogen_kg', models.FloatField()),
                ('phosphorus_kg', models.FloatField()),
                ('potassium_kg', models.FloatField()),
                ('recommendation', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fertilizer_calculations',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('disease_name', models.CharField(max_length=150)),
                ('crop_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('faible', 'Faible'), ('modérée', 'Modérée'), ('élevée', 'Élevée'), ('critique', 'Critique')], default='modérée', max_length=10)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('location_label', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alerts/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('traitée', 'Traitée')], default='active', max_length=10)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.cropscan')),
            ],
            options={
                'db_table': 'health_alerts',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
