# Generated by Django 5.1.4 on 2026-07-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropscan',
            options={'ordering': ['-created_date'], 'verbose_name': 'Scan de culture', 'verbose_name_plural': 'Scans de culture'},
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AlterModelOptions(
            name='expertmessage',
            options={'ordering': ['created_date'], 'verbose_name': 'Message expert', 'verbose_name_plural': 'Messages experts'},
        ),
        migrations.AlterModelOptions(
            name='fertilizercalculation',
            options={'ordering': ['-created_date'], 'verbose_name': "Calcul d'engrais", 'verbose_name_plural': "Calculs d'engrais"},
        ),
        migrations.AlterModelOptions(
            name='healthalert',
            options={'ordering': ['-created_date'], 'verbose_name': 'Alerte sanitaire', 'verbose_name_plural': 'Alertes sanitaires'},
        ),
        migrations.AlterModelOptions(
            name='onetimecode',
            options={'verbose_name': 'Code à usage unique', 'verbose_name_plural': 'Codes à usage unique'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='expert',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone'),
        ),
        migrations.AddField(
            model_name='expert',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='avatar_color',
            field=models.CharField(default='#2D5A3D', max_length=10, verbose_name='couleur avatar'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='location',
            field=models.CharField(max_length=100, verbose_name='localisation'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='online',
            field=models.BooleanField(default=True, verbose_name='en ligne'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='role',
            field=models.CharField(choices=[('Médecin de plantes', 'Médecin de plantes'), ('Vétérinaire', 'Vétérinaire')], max_length=30, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='specialty',
            field=models.CharField(max_length=200, verbose_name='spécialité'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nom complet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='membre du staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('dioula', 'Dioula'), ('baoule', 'Baoulé'), ('bete', 'Bété'), ('senoufo', 'Sénoufo')], default='fr', max_length=20, verbose_name='langue préférée'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur')], default='user', max_length=10, verbose_name='rôle'),
        ),
    ]
