# Generated by Django 5.1.4 on 2026-07-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cropscan_options_alter_expert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='experts/photos/', verbose_name='photo'),
        ),
    ]
