# Generated by Django 5.1.4 on 2026-07-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cropscantracking_cropscan_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropscan',
            name='dosage',
            field=models.TextField(blank=True),
        ),
    ]
